apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-spring-gateway
spec:
  title: Building a Gateway with Spring
  description: Getting started with Spring Cloud Gateway
  vendor: eduk8s.io
  difficulty: beginner
  duration: 15m
  url: github.com/everythingeverywhere/lab-spring-gateway
  content:
    image:  quay.io/eduk8s/jdk8-environment:master
    files: github.com/everythingeverywhere/lab-spring-gateway
  session:
    budget: medium
    applications:
      console:
        enabled: true
      editor:
        enabled: true
